import type { ClinicalTrial } from "./types.js";

export const trials: ClinicalTrial[] = [
  {
    id: "NCT-001",
    name: "AURORA-1: Pocenbrodib in mCRPC",
    sponsor: "Pathos Therapeutics",
    phase: "II",
    status: "recruiting",
    indication: "Metastatic castration-resistant prostate cancer",
    primaryEndpoint: "Radiographic progression-free survival at 12 months",
    enrollment: 180,
    startDate: "2023-03-15",
    estimatedCompletionDate: "2025-09-01",
    adverseEventRate: 31.2,
    responseRate: 38.5,
    keyFindings: [
      "Interim analysis at 6 months shows 38.5% PSA50 response rate",
      "Grade 3+ adverse events in 31.2% of patients, primarily fatigue and nausea",
      "No dose-limiting toxicities at the 400mg BID dose level",
    ],
  },
  {
    id: "NCT-002",
    name: "BEACON-3: Vemurafenib + Cobimetinib in Melanoma",
    sponsor: "Genentech",
    phase: "III",
    status: "completed",
    indication: "BRAF V600E-mutant unresectable melanoma",
    primaryEndpoint: "Overall survival",
    enrollment: 495,
    startDate: "2020-06-01",
    estimatedCompletionDate: "2024-01-15",
    adverseEventRate: 58.4,
    responseRate: 61.3,
    keyFindings: [
      "Median OS of 22.5 months vs 17.4 months for vemurafenib monotherapy",
      "ORR of 61.3% vs 45.0% for combination vs monotherapy",
      "Photosensitivity in 41% of patients required dose modification",
    ],
  },
  {
    id: "NCT-003",
    name: "CLARITY-1: Novel BET Inhibitor FT-9001 Phase I Dose Escalation",
    sponsor: "Pathos Therapeutics",
    phase: "I",
    status: "recruiting",
    indication: "Advanced solid tumors with MYC amplification",
    primaryEndpoint: "Maximum tolerated dose and recommended Phase II dose",
    enrollment: 45,
    startDate: "2024-01-10",
    estimatedCompletionDate: "2025-12-31",
    adverseEventRate: 22.0,
    responseRate: null,
    keyFindings: [
      "Three dose cohorts completed (50mg, 100mg, 200mg QD)",
      "No DLTs observed at any dose level to date",
      "Preliminary PK data shows dose-proportional exposure",
    ],
  },
  {
    id: "NCT-004",
    name: "SUMMIT: Neratinib in HER2-mutant Solid Tumors",
    sponsor: "Puma Biotechnology",
    phase: "II",
    status: "completed",
    indication: "HER2-mutant non-breast solid tumors",
    primaryEndpoint: "Objective response rate",
    enrollment: 141,
    startDate: "2018-11-01",
    estimatedCompletionDate: "2022-05-20",
    adverseEventRate: 44.7,
    responseRate: 28.0,
    keyFindings: [
      "28% ORR across all tumor types with HER2 mutations",
      "Highest ORR in biliary tract (34%) and cervical (29%) cancers",
      "Diarrhea management protocol reduced grade 3+ events from 33% to 7%",
    ],
  },
  {
];
